export const ActionTypes = {
  //product  
  SET_PRODUCTS: "SET_PRODUCTS",
    EDIT_PRODUCTS: "EDIT_PRODUCTS",
    DEL_PRODUCTS: "DEL_PRODUCTS",

    //client
    LIST_CLIENT_DATA_REMAIN: "LIST_CLIENT_DATA_REMAIN",
    LIST_CLIENT_ORDER_DETAIL: "LIST_CLIENT_ORDER_DETAIL",
  };