export const ActionTypes = {
  //product
  SET_PRODUCTS: 'SET_PRODUCTS',
  EDIT_PRODUCTS: 'EDIT_PRODUCTS',
  DEL_PRODUCTS: 'DEL_PRODUCTS',

  //client
  DETAIL_CLIENTS: 'DETAIL_CLIENTS',
  DETAIL_CLIENT_AFTER_DELETE_PRODUCT: 'DETAIL_CLIENT_AFTER_DELETE_PRODUCT',
  DETAIL_CLIENT_AFTER_EDIT_PRODUCT: 'DETAIL_CLIENT_AFTER_EDIT_PRODUCT',
  
  //client
  SET_EMPLOYEE: 'SET_EMPLOYEE',
  // DETAIL_CLIENT_AFTER_DELETE_PRODUCT: 'DETAIL_CLIENT_AFTER_DELETE_PRODUCT',
  // DETAIL_CLIENT_AFTER_EDIT_PRODUCT: 'DETAIL_CLIENT_AFTER_EDIT_PRODUCT',
};
